### ISSUE TITLE
[SUGGESTION] more algos and GPUs

### ISSUE THREAD

**Issue by forart** [TransparentLC/realesrgan-gui#33]
Hi there, very nice project !

It would be cool to use it to apply other upscaling (and not only) algorithms, so a collaboration with @mafiosnik777's [enhancr](https://github.com/mafiosnik777/enhancr#readme) project could help:
![](https://camo.githubusercontent.com/b96d020a8183077b8b7b8c9d0b0cdaf4f103060a7bc379a7a98a185d3916dcd2/68747470733a2f2f6d6166696f736e696b2e6e656564736d656e74616c2e68656c702f31774c474837437845412e706e673f6b65793d756b374d3754616f6c4143697071)

Anyway, enhancr relays on @cszn's [DPIR](https://github.com/cszn/DPIR) for denoising, that - while interesting - is a bit limited...

...it would be great to have more denoising options as [Aydin](https://github.com/royerlab/aydin/#readme) offers:
![](https://royerlab.github.io/aydin/v0.1.15/_images/aydin_welcome_screen.png)

Hope that inspires !

**Comment by TransparentLC** [comment]
Thank you for your support!

However, I have no plans to integrate algorithms other than Real-ESRGAN in the near future. I used to be a user of [Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI), another all-in-one GUI similar to enhancr you may have heard of. But since it is too heavy and complex and I only use a small part of its features, I created this repo to write another GUI targeting simplicity and lightweight, maybe some users will prefer that as well.

BTW, Aydin's denoising looks great, I may use it in the future when processing images, thanks for the recommendation : )

**Comment by hyrulelinks** [comment]
aydin's dependence is huge, close to 1GB, and if integrated into this project, the size of the program will increase significantly, and it is debatable whether the noise reduction effect matches this volume
