### ISSUE TITLE
Replacing `tkinterdnd2-universal` with `tkinterdnd2`

### ISSUE THREAD

**Issue by NandeMD** [TransparentLC/realesrgan-gui#92]
I'm suggesting to replace [tkinterdnd2-universal](https://pypi.org/project/tkinterdnd2-universal/) package to [tkinterdnd2](https://github.com/Eliav2/tkinterdnd2).  

 `tkinterdnd2-universal` is not maintained and it is defunct. Also user @blacklein seems like deleted the account. Repo: https://github.com/blacklein/tkinterdnd2-universal

I found a drop-in replacement: [tkinterdnd2](https://github.com/Eliav2/tkinterdnd2). It is maintained and if we have issues, we can just open an issue. (There is no `tkinterdnd2-universal` repository.) I tested it on Ubuntu 22.04.5 LTS x86_64 and it is working for me.

Note: I was trying to solve an issue about running tkinter apps with uv and wanted to send a PR for a work-around but could not access  tkinterdnd2-universal repository. Then i found [tkinterdnd2](https://github.com/Eliav2/tkinterdnd2).

tkinterdnd2 links:
- [Repository](https://github.com/Eliav2/tkinterdnd2)
- [PyPi](https://pypi.org/project/tkinterdnd2/)

**Comment by NandeMD** [comment]
@TransparentLC

**Comment by TransparentLC** [comment]
https://github.com/TransparentLC/realesrgan-gui/commit/b465a0a680c84f9bf904ea2c658cc78b204b0e7d

Actually, tkinterdnd2 is used at first. @blacklein suggested using tkinterdnd2-universal because of Apple's ARM CPUs like M1.

It seems that Apple's ARM binaries are included in tkinterdnd2 now. I will edit the requirements.txt and build scripts (if needed) when I am free, or are you glad to make a PR for that?

I don't know why @blacklein deleted his account. But I still thank him for his support for macOS-related things.

**Comment by NandeMD** [comment]
Okay, I will open a PR tomorrow.
